---

- name: Include variables
  include_vars: vars.yml

- name: Install apache
  yum: name=httpd update_cache=yes state=latest 

- name: Turn apache on
  service: name=httpd state=started enabled=yes

- name: Make Apache Root directory
  file:
      path: "/var/www/{{ http_host }}"
      state: directory
      owner: "apache"
      group: "apache"
      mode: '0755'

- name: Set up Apache VirtualHost
  template:
      src: "files/httpd.conf"
      dest: "/etc/httpd/conf.d/{{ http_conf }}"
      owner: root
      group: root
      mode: u=rw,g=r,o=r
