---
- hosts: app
  become: yes

  tasks:
        - name: Include variables
          include_vars: vars.yml

        - name: Install apache
          yum: name=httpd update_cache=yes state=latest
        
        - name: Disable firewall
          service: name=firewalld state=stopped enabled=no

        - name: Turn apache on
          service: name=httpd state=started enabled=yes

        - name: Make Apache Root directory
          file:
                  path: "/var/www/{{ http_host }}"
                  state: directory
                  owner: "apache"
                  group: "apache"
                  mode: '0755'

        - name: Set up Apache VirtualHost
          template:
                  src: "files/httpd.conf"
                  dest: "/etc/httpd/conf.d/{{ http_conf }}"
                  owner: root
                  group: root
                  mode: u=rw,g=r,o=r

        - name: Install EPEL
          yum: name=epel-release.noarch state=latest

        - name: Install PHP Remi Repo
          yum: name=http://rpms.remirepo.net/enterprise/remi-release-7.rpm update_cache=yes state=latest

        - name: Enable PHP Remi
          yum: enablerepo=remi,remi-php56      

        - name: Install PHP extensions
          yum: name={{ item }} update_cache=yes state=latest
          loop: "{{ php_modules }}"
